export const standardsData = {
  headers: {
    ISO146444: "ISO 14644-4",
    FDA209E: "FDA 209E",
    GMP: "GMP",
    JISB9920: "JIS B 9920",
    EUGMP: "EU GMP",
    TGA: "TGA",
    BS5295: "BS 5295",
    GERMANYVD: "GERMANY VD",
    AFNORX44101: "AFNOR X44101",
    NC: "NC-Non Classified",
    ISO14698: "ISO 14698",
    SCHEDULEM: "SCHEDULE M",
  },
  rows: [
    {
      ISO146444: "ISO 9",
      FDA209E: "Class100K",
      GMP: "Grade D (ISO 8 at Rest & Not Defined)",
      JISB9920: "JIS Class 9",
      EUGMP: "EU GMP - Grade D (ISO 7 at Rest & ISO 8 in Oper.)",
      TGA: "3500",
      BS5295: "K",
      GERMANYVD: "6",
      AFNORX44101: "4000000",
      NC: "20µ",
      ISO14698: "BSL - 1",
      SCHEDULEM: "GRADE CLASS D",
    },
    {
      ISO146444: "ISO 8",
      FDA209E: "Class10K",
      GMP: "Grade C (ISO 7 at Rest & ISO 8 in Oper.)",
      JISB9920: "JIS Class 8",
      EUGMP: "EU GMP - Grade C (ISO 7 at Rest & ISO 7 in Oper.)",
      TGA: "350",
      BS5295: "J",
      GERMANYVD: "5",
      AFNORX44101: "400000",
      NC: "15µ",
      ISO14698: "BSL - 2",
      SCHEDULEM: "GRADE CLASS C",
    },
    {
      ISO146444: "ISO 7",
      FDA209E: "Class1K",
      GMP: "Grade B (ISO 5 at Rest & ISO 7 in Oper.)",
      JISB9920: "JIS Class 7",
      EUGMP: "EU GMP - Grade B (ISO 5 at Rest & ISO 7 in Oper.)",
      TGA: "35",
      BS5295: "G or H",
      GERMANYVD: "4",
      AFNORX44101: "4000",
      NC: "10µ",
      ISO14698: "BSL - 3",
      SCHEDULEM: "GRADE CLASS B",
    },
    {
      ISO146444: "ISO 6",
      FDA209E: "Class 100",
      GMP: "Grade A (ISO 5 at Rest & ISO 5 in Oper.)",
      JISB9920: "JIS Class 6",
      EUGMP: "EU GMP - Grade A (ISO 5 at Rest & ISO 5 in Oper.)",
      TGA: "3.5",
      BS5295: "E or F",
      GERMANYVD: "3",
      AFNORX44101: null,
      NC: "5µ",
      ISO14698: "BSL - 4",
      SCHEDULEM: "GRADE CLASS A",
    },
    {
      ISO146444: "ISO 5",
      FDA209E: "Class 10",
      GMP: null,
      JISB9920: "JIS Class 5",
      EUGMP: null,
      TGA: "0.35",
      BS5295: "D",
      GERMANYVD: "2",
      AFNORX44101: "4000",
      NC: "1µ",
      ISO14698: null,
      SCHEDULEM: null,
    },
    {
      ISO146444: "ISO 4",
      FDA209E: "Class 1",
      GMP: null,
      JISB9920: "JIS Class 4",
      EUGMP: null,
      TGA: "0.035",
      BS5295: "C",
      GERMANYVD: "1",
      AFNORX44101: null,
      NC: "No-Filtration",
      ISO14698: null,
      SCHEDULEM: null,
    },
    {
      ISO146444: "ISO 3",
      FDA209E: null,
      GMP: null,
      JISB9920: "JIS Class 3",
      EUGMP: null,
      TGA: null,
      BS5295: null,
      GERMANYVD: "0",
      AFNORX44101: null,
      NC: "Positive Pressure",
      ISO14698: null,
      SCHEDULEM: null,
    },
    {
      ISO146444: "ISO 2",
      FDA209E: null,
      GMP: null,
      JISB9920: "JIS Class 2",
      EUGMP: null,
      TGA: null,
      BS5295: null,
      GERMANYVD: "0",
      AFNORX44101: null,
      NC: "Exhaust",
      ISO14698: null,
      SCHEDULEM: null,
    },
    {
      ISO146444: "ISO 1",
      FDA209E: null,
      GMP: null,
      JISB9920: null,
      EUGMP: null,
      TGA: null,
      BS5295: null,
      GERMANYVD: null,
      AFNORX44101: null,
      NC: null,
      ISO14698: null,
      SCHEDULEM: null,
    },
  ],
}

export const filterOptions = {
  column1: ["20 M Supply", "20 M Exhaust", "10 M Supply", "10 M Exhaust", "5 M Supply", "5 M Exhaust", "1 M Supply"],
  column2: [
    "1 M Exhaust",
    "0.3 M HEPA 95% Supply",
    "0.3 M HEPA 95% Exhaust",
    "0.3 M HEPA 99.97% Supply",
    "0.3 M HEPA 99.97% Exhaust",
    "0.12 M ULPA 99.995% Supply",
    "0.12 M ULPA 99.995% Exhaust",
  ],
}

export const ahuSpecOptions = [
  "25mm Thick Panel & AL Profile",
  "Panels with both side 24G Precoated GI Sheet",
  "Aluminium Profile VCD for Fresh Air- Supply Air & Return Air",
  "Fire Control Damper for Supply & Return Air",
  "Variable Frequency Drive (VFD) - Not Required",
  "Pressure Guage (0-25mm) for 5 Micr Filter Section",
]

// Data derived from the user's "Bill of Design" CSV file.
// Default selections are set to produce the correct total of 145.
export const pressureDropData = [
  {
    initialValue: "0",
    code: "d29",
    description: "Pressure Guage (0-25mm) for 10 Micr Filter Section",
    pressureDrop: "5",
    guageSelected: "8 / 0-25",
    selected: false,
  },
  {
    initialValue: "0",
    code: "d30",
    description: "Pressure Guage (0-25mm) for 5 Micr Filter Section",
    pressureDrop: "6",
    guageSelected: "12 / 0-25",
    selected: false,
  },
  {
    initialValue: "12",
    code: "d31",
    description: "Pressure Guage (0-25mm) for 1 Micr Filter Section",
    pressureDrop: "8",
    guageSelected: "18 / 0-25",
    selected: false,
  },
  {
    initialValue: "0",
    code: "d32",
    description: "Pressure Guage (0-100 mm) for 0.3 Mic HEPA Filter Section",
    pressureDrop: "10",
    guageSelected: "20 / 0-25",
    selected: false,
  },
  {
    initialValue: "18",
    code: "d33",
    description: "Pressure Guages For All 10, 5, 1, & 0.3(HEPA) Micr Filter Sections",
    pressureDrop: "18",
    guageSelected: "50 / 0-50",
    selected: false,
  },
  {
    initialValue: "0",
    code: "d34",
    description: "Item",
    pressureDrop: "15",
    guageSelected: "25 / 0-50",
    selected: false,
  },
  {
    initialValue: "20",
    code: "d35",
    description: "Pressure Drop for 20 Micr Filter (150 mm / 100 mm Thick )",
    pressureDrop: "15",
    guageSelected: "25 / 0-50",
    selected: true,
  },
  {
    initialValue: "0",
    code: "e29",
    description: "Pressure Drop for 10 Micr Filter ( 150 mm Thick )",
    pressureDrop: "",
    guageSelected: "",
    selected: false,
  },
  {
    initialValue: "50",
    code: "e30",
    description: "Pressure Drop for 5 Micr Filter ( 300 mm Thick )",
    pressureDrop: "",
    guageSelected: "",
    selected: true,
  },
  {
    initialValue: "0",
    code: "e31",
    description: "Pressure Drop for 1 Micr Filter ( 300 mm Thick )",
    pressureDrop: "",
    guageSelected: "",
    selected: false,
  },
  {
    initialValue: "0",
    code: "e32",
    description: "Pressure Drop for 0.3 Micr Filter 95% Eff ( 300 mm Thick )",
    pressureDrop: "",
    guageSelected: "",
    selected: false,
  },
  {
    initialValue: "0",
    code: "e33",
    description: "Pressure Drop for 0.3 Micr Filter 99.97% Eff (150 mm Thick)",
    pressureDrop: "",
    guageSelected: "",
    selected: false,
  },
  {
    initialValue: "0",
    code: "e34",
    description: "Pressure Drop for 0.12 Micr Filter 99.995% Eff ( 70-150 mm Thick )",
    pressureDrop: "",
    guageSelected: "",
    selected: false,
  },
  {
    initialValue: "0",
    code: "e35",
    description: "Terminal Return Air Filters and suctional pressure drop",
    pressureDrop: "12",
    guageSelected: "25",
    selected: false,
  },
  {
    initialValue: "15",
    code: "j43",
    description: "Pressure Drop for 100' distance in ducting",
    pressureDrop: "",
    guageSelected: "",
    selected: true,
  },
  {
    initialValue: "10",
    code: "j42",
    description: "Cowls, Bends, Elbows, offsets,collars,plenums,Y Branches,grills,etc",
    pressureDrop: "12",
    guageSelected: "25",
    selected: true,
  },
  {
    initialValue: "0",
    code: "j45",
    description: "each one will have a 0.5 mm PD with quantity*0.5 mm approx",
    pressureDrop: "24",
    guageSelected: "50",
    selected: false,
  },
  {
    initialValue: "50",
    code: "j46",
    description: "Total Pressure drop in ducting approximately",
    pressureDrop: "",
    guageSelected: "",
    selected: true,
  },
]
